name: openweatherapp
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.0
  http: ^0.13.6
  flutter_dotenv: ^5.1.0
  font_awesome_flutter: ^10.7.0
  equatable: ^2.0.5
  geolocator: ^13.0.1
  google_maps_flutter: ^2.10.0
  dartz: ^0.10.1
  intl: ^0.19.0
  google_fonts: 4.0.4
  go_router: ^14.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - .env
